services:
  article-management:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: article_management_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - article-management-data:/var/lib/postgresql/data
    networks:
      - article-management-network

  article-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://article-management:5432/article_management_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - article-management
    networks:
      - article-management-network

volumes:
  article-management-data:
networks:
  article-management-network: