spring:
  application:
    name: article-management

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5444/article_management_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
